#!/usr/bin/env bash
# Transfers a file from a client to a server
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

if [ $# -lt 4 ]
  then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username"@"$server_ip":~/
fi
