#!/usr/bin/env bash
# Install nginx web server
apt update
apt install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }

    location / {
	root /var/www/html;
	index index.nginx-debian.html;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
