#!/usr/bin/env bash
# Install and configure nginx web server

# shellcheck disable=SC2154

apt update
apt install -y nginx

printf "%s\n\n" "Ceci n'est pas une page" > /var/www/html/custom_404.html

printf "%s\n" "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    add_header X-Served-By \$hostname;

    location / {
        return 200 'Hello World!\n';
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
