#!/usr/bin/env bash
# Install and Configure HAproxy on a server

apt update
apt install -y haproxy

# Backup original config file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg << EOL
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend hbnb-http-front
        bind *:80
        mode http
        default_backend hbnb-http-back

backend hbnb-http-back
        mode http
        balance roundrobin
        server web-01 34.207.61.201
        server web-02 52.91.178.2
EOL

# Enable HAProxy to be managed via init script
service haproxy enable

# Restart HAProxy to apply changes
service haproxy restart
