#!/usr/bin/env bash
#  Pings an IP address passed as an argument 5 times
#+ Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
#+ if no argument is passed

ARGS=$#
if [ "$ARGS" -eq 0 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
