#!/usr/bin/env bash
# Use while loop + IFS to tell the story of /etc/passwd

file_name=/etc/passwd

while IFS=":" read -r username password uid gid info home shell
do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "$file_name"
