#!/usr/bin/env bash
# Displays numbers from 1 to 20
# Displays 4 then "bad luck from China" for 4th iteration
# Displays 9 then "bad luck from Japan" for 9th iteration
# Displays 17 then "back luck from Italy for 17th iteration

i=1
while [ "$i" -le 20 ]
do
  echo "$i"

  case "$i" in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
    *)
      ;;
  esac

  ((i++))
done
