#!/usr/bin/env bash
# Reloads gunicorn in a graceful way
# shellcheck disable=SC2009

# ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP
ps aux | grep '[g]unicorn' | awk '{ print $2 }' | xargs kill -HUP
# pgrep '[g]unicorn' | awk '{ print $2 }' | xargs -r kill -HUP
# pgrep '[g]unicorn' | xargs -r kill -HUP
